-- E-COMMERCE ORDER MANAGEMENT SYSTEM
-- ORACLE DDL

CREATE TABLE Customer (
    Customer_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Name VARCHAR2(100) NOT NULL,
    Email VARCHAR2(100) UNIQUE NOT NULL,
    Phone VARCHAR2(15),
    Address VARCHAR2(200),
    CONSTRAINT pk_customer PRIMARY KEY (Customer_ID)
);

CREATE TABLE Category (
    Category_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Category_Name VARCHAR2(100) NOT NULL UNIQUE,
    Description VARCHAR2(200),
    CONSTRAINT pk_category PRIMARY KEY (Category_ID)
);

CREATE TABLE Supplier (
    Supplier_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Supplier_Name VARCHAR2(100) NOT NULL,
    Contact VARCHAR2(15) NOT NULL,
    Email VARCHAR2(100) UNIQUE,
    Address VARCHAR2(200),
    CONSTRAINT pk_supplier PRIMARY KEY (Supplier_ID)
);

CREATE TABLE Product (
    Product_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Product_Name VARCHAR2(100) NOT NULL,
    Price NUMBER(10,2) NOT NULL,
    Stock_Quantity NUMBER DEFAULT 0 NOT NULL,
    Category_ID NUMBER NOT NULL,
    CONSTRAINT pk_product PRIMARY KEY (Product_ID),
    CONSTRAINT fk_product_category
        FOREIGN KEY (Category_ID)
        REFERENCES Category(Category_ID),
    CONSTRAINT chk_product_price CHECK (Price >= 0),
    CONSTRAINT chk_product_stock CHECK (Stock_Quantity >= 0)
);

CREATE TABLE Address (
    Address_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Customer_ID NUMBER NOT NULL,
    Street VARCHAR2(200),
    City VARCHAR2(100),
    State VARCHAR2(100),
    Pincode VARCHAR2(10),
    Address_Type VARCHAR2(20),
    CONSTRAINT pk_address PRIMARY KEY (Address_ID),
    CONSTRAINT fk_address_customer
        FOREIGN KEY (Customer_ID)
        REFERENCES Customer(Customer_ID)
);

CREATE TABLE Orders (
    Order_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Customer_ID NUMBER NOT NULL,
    Address_ID NUMBER,
    Order_Date DATE DEFAULT SYSDATE NOT NULL,
    Order_Status VARCHAR2(30) DEFAULT 'Pending' NOT NULL,
    Total_Amount NUMBER(10,2) NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (Order_ID),
    CONSTRAINT fk_orders_customer
        FOREIGN KEY (Customer_ID)
        REFERENCES Customer(Customer_ID),
    CONSTRAINT fk_orders_address
        FOREIGN KEY (Address_ID)
        REFERENCES Address(Address_ID),
    CONSTRAINT chk_order_amount CHECK (Total_Amount >= 0)
);

CREATE TABLE Order_Item (
    Order_Item_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Order_ID NUMBER NOT NULL,
    Product_ID NUMBER NOT NULL,
    Quantity NUMBER NOT NULL,
    Unit_Price NUMBER(10,2) NOT NULL,
    CONSTRAINT pk_order_item PRIMARY KEY (Order_Item_ID),
    CONSTRAINT fk_item_order
        FOREIGN KEY (Order_ID)
        REFERENCES Orders(Order_ID),
    CONSTRAINT fk_item_product
        FOREIGN KEY (Product_ID)
        REFERENCES Product(Product_ID),
    CONSTRAINT chk_item_quantity CHECK (Quantity > 0),
    CONSTRAINT chk_item_price CHECK (Unit_Price >= 0)
);

CREATE TABLE Delivery (
    Delivery_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Order_ID NUMBER NOT NULL UNIQUE,
    Delivery_Address VARCHAR2(200) NOT NULL,
    Delivery_Date DATE,
    Delivery_Status VARCHAR2(30) DEFAULT 'Pending' NOT NULL,
    CONSTRAINT pk_delivery PRIMARY KEY (Delivery_ID),
    CONSTRAINT fk_delivery_order
        FOREIGN KEY (Order_ID)
        REFERENCES Orders(Order_ID)
);

CREATE TABLE Payment (
    Payment_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Order_ID NUMBER NOT NULL UNIQUE,
    Payment_Date DATE,
    Payment_Method VARCHAR2(30) NOT NULL,
    Payment_Status VARCHAR2(30) DEFAULT 'Pending' NOT NULL,
    CONSTRAINT pk_payment PRIMARY KEY (Payment_ID),
    CONSTRAINT fk_payment_order
        FOREIGN KEY (Order_ID)
        REFERENCES Orders(Order_ID)
);

-- ADDITIONAL CONSTRAINTS

ALTER TABLE Customer
ADD CONSTRAINT uq_customer_email UNIQUE (Email);

ALTER TABLE Category
ADD CONSTRAINT uq_category_name UNIQUE (Category_Name);

ALTER TABLE Supplier
ADD CONSTRAINT uq_supplier_email UNIQUE (Email);

ALTER TABLE Delivery
ADD CONSTRAINT chk_delivery_status
CHECK (Delivery_Status IN
('Pending','Shipped','Delivered','Cancelled'));

ALTER TABLE Payment
ADD CONSTRAINT chk_payment_status
CHECK (Payment_Status IN
('Pending','Paid','Failed','Refunded'));

ALTER TABLE Orders
ADD CONSTRAINT chk_order_status
CHECK (Order_Status IN
('Pending','Processing','Shipped','Delivered','Cancelled'));

ALTER TABLE Payment
ADD CONSTRAINT chk_payment_method
CHECK (Payment_Method IN
('UPI','Card','COD','NetBanking'));

-- INDEXES FOR FASTER RETRIEVAL

CREATE INDEX idx_product_category
ON Product(Category_ID);

CREATE INDEX idx_orders_customer
ON Orders(Customer_ID);

CREATE INDEX idx_orderitem_order
ON Order_Item(Order_ID);

CREATE INDEX idx_orderitem_product
ON Order_Item(Product_ID);

CREATE INDEX idx_payment_order
ON Payment(Order_ID);

CREATE INDEX idx_delivery_order
ON Delivery(Order_ID);
