
-- 1. CUSTOMER TABLE

CREATE TABLE Customer (
    Customer_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Email VARCHAR2(100) NOT NULL UNIQUE,
    Phone VARCHAR2(15),
    Address VARCHAR2(200)
);

-- 2. CATEGORY TABLE

CREATE TABLE Category (
    Category_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    Category_Name VARCHAR2(100) NOT NULL UNIQUE,
    Description VARCHAR2(200)
);

-- 3. SUPPLIER TABLE

CREATE TABLE Supplier (
    Supplier_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    Supplier_Name VARCHAR2(100) NOT NULL,
    Contact VARCHAR2(15) NOT NULL,
    Email VARCHAR2(100) UNIQUE,
    Address VARCHAR2(200)
);

-- 4. PRODUCT TABLE

CREATE TABLE Product (
    Product_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    Product_Name VARCHAR2(100) NOT NULL,
    Price NUMBER(10,2) NOT NULL,
    Stock_Quantity NUMBER NOT NULL DEFAULT 0,
    Category_ID NUMBER NOT NULL,

    CONSTRAINT fk_product_category
        FOREIGN KEY (Category_ID)
        REFERENCES Category(Category_ID)
);

-- 5. ORDERS TABLE

CREATE TABLE Orders (
    Order_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    Customer_ID NUMBER NOT NULL,
    Order_Date DATE NOT NULL DEFAULT SYSDATE,
    Order_Status VARCHAR2(30) NOT NULL DEFAULT 'Pending',
    Total_Amount NUMBER(10,2) NOT NULL,

    CONSTRAINT fk_orders_customer
        FOREIGN KEY (Customer_ID)
        REFERENCES Customer(Customer_ID)
);

-- 6. ORDER_ITEM TABLE

CREATE TABLE Order_Item (
    Order_Item_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    Order_ID NUMBER NOT NULL,
    Product_ID NUMBER NOT NULL,
    Quantity NUMBER NOT NULL,
    Unit_Price NUMBER(10,2) NOT NULL,

    CONSTRAINT fk_orderitem_order
        FOREIGN KEY (Order_ID)
        REFERENCES Orders(Order_ID),

    CONSTRAINT fk_orderitem_product
        FOREIGN KEY (Product_ID)
        REFERENCES Product(Product_ID)
);

-- 7. DELIVERY TABLE

CREATE TABLE Delivery (
    Delivery_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    Order_ID NUMBER NOT NULL UNIQUE,
    Delivery_Address VARCHAR2(200) NOT NULL,
    Delivery_Date DATE,
    Delivery_Status VARCHAR2(30) NOT NULL DEFAULT 'Pending',

    CONSTRAINT fk_delivery_order
        FOREIGN KEY (Order_ID)
        REFERENCES Orders(Order_ID)
);

-- 8. PAYMENT TABLE

CREATE TABLE Payment (
    Payment_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    Order_ID NUMBER NOT NULL UNIQUE,
    Payment_Date DATE,
    Payment_Method VARCHAR2(30) NOT NULL,
    Payment_Status VARCHAR2(30) NOT NULL DEFAULT 'Pending',

    CONSTRAINT fk_payment_order
        FOREIGN KEY (Order_ID)
        REFERENCES Orders(Order_ID)
);

-- 9. CHECK CONSTRAINTS

-- Product price must not be negative

ALTER TABLE Product
ADD CONSTRAINT chk_product_price
CHECK (Price >= 0);

-- Product stock must not be negative

ALTER TABLE Product
ADD CONSTRAINT chk_product_stock
CHECK (Stock_Quantity >= 0);

-- Order total amount must not be negative

ALTER TABLE Orders
ADD CONSTRAINT chk_order_amount
CHECK (Total_Amount >= 0);

-- Order item quantity must be greater than zero

ALTER TABLE Order_Item
ADD CONSTRAINT chk_quantity
CHECK (Quantity > 0);


-- Order item unit price must not be negative

ALTER TABLE Order_Item
ADD CONSTRAINT chk_unit_price
CHECK (Unit_Price >= 0);

-- 10. ADDITIONAL TABLE COMMENTS

COMMENT ON TABLE Customer IS
'E-Commerce customer information';

COMMENT ON TABLE Category IS
'Product category information';

COMMENT ON TABLE Supplier IS
'Supplier information';

COMMENT ON TABLE Product IS
'Products available in the e-commerce system';

COMMENT ON TABLE Orders IS
'Customer order information';

COMMENT ON TABLE Order_Item IS
'Individual products included in each order';

COMMENT ON TABLE Delivery IS
'Delivery information for customer orders';

COMMENT ON TABLE Payment IS
'Payment information for customer orders';

-- 11. COLUMN COMMENTS

COMMENT ON COLUMN Customer.Customer_ID IS
'Unique customer identifier';

COMMENT ON COLUMN Customer.Name IS
'Customer full name';

COMMENT ON COLUMN Customer.Email IS
'Customer email address';

COMMENT ON COLUMN Customer.Phone IS
'Customer phone number';

COMMENT ON COLUMN Customer.Address IS
'Customer address';


COMMENT ON COLUMN Category.Category_ID IS
'Unique category identifier';

COMMENT ON COLUMN Category.Category_Name IS
'Name of the product category';

COMMENT ON COLUMN Category.Description IS
'Description of the category';


COMMENT ON COLUMN Supplier.Supplier_ID IS
'Unique supplier identifier';

COMMENT ON COLUMN Supplier.Supplier_Name IS
'Name of the supplier';

COMMENT ON COLUMN Supplier.Contact IS
'Supplier contact number';

COMMENT ON COLUMN Supplier.Email IS
'Supplier email address';

COMMENT ON COLUMN Supplier.Address IS
'Supplier address';


COMMENT ON COLUMN Product.Product_ID IS
'Unique product identifier';

COMMENT ON COLUMN Product.Product_Name IS
'Name of the product';

COMMENT ON COLUMN Product.Price IS
'Price of the product';

COMMENT ON COLUMN Product.Stock_Quantity IS
'Available product stock';

COMMENT ON COLUMN Product.Category_ID IS
'Category associated with the product';


COMMENT ON COLUMN Orders.Order_ID IS
'Unique order identifier';

COMMENT ON COLUMN Orders.Customer_ID IS
'Customer who placed the order';

COMMENT ON COLUMN Orders.Order_Date IS
'Date on which the order was placed';

COMMENT ON COLUMN Orders.Order_Status IS
'Current status of the order';

COMMENT ON COLUMN Orders.Total_Amount IS
'Total amount of the order';


COMMENT ON COLUMN Order_Item.Order_Item_ID IS
'Unique order item identifier';

COMMENT ON COLUMN Order_Item.Order_ID IS
'Order associated with the item';

COMMENT ON COLUMN Order_Item.Product_ID IS
'Product included in the order';

COMMENT ON COLUMN Order_Item.Quantity IS
'Quantity of the product ordered';

COMMENT ON COLUMN Order_Item.Unit_Price IS
'Price of one unit of the product';


COMMENT ON COLUMN Delivery.Delivery_ID IS
'Unique delivery identifier';

COMMENT ON COLUMN Delivery.Order_ID IS
'Order associated with the delivery';

COMMENT ON COLUMN Delivery.Delivery_Address IS
'Address where the order is delivered';

COMMENT ON COLUMN Delivery.Delivery_Date IS
'Date of delivery';

COMMENT ON COLUMN Delivery.Delivery_Status IS
'Current delivery status';


COMMENT ON COLUMN Payment.Payment_ID IS
'Unique payment identifier';

COMMENT ON COLUMN Payment.Order_ID IS
'Order associated with the payment';

COMMENT ON COLUMN Payment.Payment_Date IS
'Date of payment';

COMMENT ON COLUMN Payment.Payment_Method IS
'Method used for payment';

COMMENT ON COLUMN Payment.Payment_Status IS
'Current payment status';

-- 12. VERIFY TABLES

SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME IN (
    'CUSTOMER',
    'CATEGORY',
    'SUPPLIER',
    'PRODUCT',
    'ORDERS',
    'ORDER_ITEM',
    'DELIVERY',
    'PAYMENT'
)
ORDER BY TABLE_NAME;

-- 13. VERIFY CONSTRAINTS


SELECT
    CONSTRAINT_NAME,
    CONSTRAINT_TYPE,
    TABLE_NAME,
    STATUS
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN (
    'CUSTOMER',
    'CATEGORY',
    'SUPPLIER',
    'PRODUCT',
    'ORDERS',
    'ORDER_ITEM',
    'DELIVERY',
    'PAYMENT'
)
ORDER BY TABLE_NAME, CONSTRAINT_NAME;
